### ISSUE TITLE
Hangs on macOS 12 Monterey

### ISSUE THREAD

**Issue by magnusviri** [wol101/GaitSym2019#2]
When selecting "About GaitSym" in the "GaitSym" menu on macOS 12 Monterey, GaitSym hangs. I'm including the results of `sample GaitSym2019`.

[GaitSym2019_2022-06-30_123631_Rjkx.sample.txt](https://github.com/wol101/GaitSym2019/files/9022534/GaitSym2019_2022-06-30_123631_Rjkx.sample.txt)

**Comment by wol101** [comment]
I've just tested this on the latest build running on an M1 mac running Ventura 13.1 and it doesn't crash for me. I'm not sure what the issue might have been but hopefully it has been fixed.
